# backend-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: node:14-alpine
        ports:
        - containerPort: 3000
        command: ["node", "server.js"]
        volumeMounts:
        - name: backend-files
          mountPath: /usr/src/app
      volumes:
      - name: backend-files
        configMap:
          name: backend-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

